#!/usr/bin/env python3
"""Regenerate bundles/workflow/rules/invoke-cursor-skills.md.

Covers every principle-* skill of the cursor/plugins source in the workflow
bundle config, plus the skills named in EXPLICIT. For each skill: fetch its
SKILL.md from upstream, check disable-model-invocation, and emit a table row
with the frontmatter description verbatim and a link to the installed skill.
Stdlib only — no pip installs in CI.
"""

import json
import os
import re
import sys
import urllib.request

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
CONFIG = os.path.join(REPO_ROOT, "bundles", "workflow", "config.json")
OUTPUT = os.path.join(REPO_ROOT, "bundles", "workflow", "rules", "invoke-cursor-skills.md")
UPSTREAM = "cursor/plugins"
BRANCH = "main"

# Skills that get a router rule on top of the auto-included principle-* set.
# Deliberately NOT here: thermo-nuclear-code-quality-review (stays user-invoked only).
EXPLICIT = [
    "make-pr-easy-to-review",
]

HEADER = """# Router rules

Generated by `bundles/workflow/scripts/update-router-rules.py` — do not edit by hand.

Good defaults, not law — the developer's word overrides anything here.

Do not invoke these skills via the Skill tool — some carry `disable-model-invocation`
and the tool refuses them. Instead, when the trigger in the first column matches,
read the linked file **in full** and apply its content.
"""


def fetch(url):
    req = urllib.request.Request(url)
    token = os.environ.get("GITHUB_TOKEN")
    if token and url.startswith("https://api.github.com/"):
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req) as resp:
        return resp.read().decode("utf-8")


def skill_paths():
    """Map skill name -> path of its SKILL.md in the upstream repo."""
    tree = json.loads(fetch(f"https://api.github.com/repos/{UPSTREAM}/git/trees/{BRANCH}?recursive=1"))
    paths = {}
    for entry in tree["tree"]:
        m = re.fullmatch(r".*/skills/([^/]+)/SKILL\.md", entry["path"])
        if m and m.group(1) not in paths:  # first match wins on duplicates
            paths[m.group(1)] = entry["path"]
    return paths


def parse_frontmatter(text):
    """Return (description, disabled) from a SKILL.md. Handles quoted,
    unquoted, and '>'-folded description values."""
    m = re.match(r"---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return "", False
    fm = m.group(1)
    disabled = bool(re.search(r"^disable-model-invocation:\s*true\s*$", fm, re.MULTILINE))
    dm = re.search(r"^description:\s*(.*)$", fm, re.MULTILINE)
    if not dm:
        return "", disabled
    value = dm.group(1).strip()
    if value in (">", ">-", "|", "|-"):
        lines = []
        for line in fm[dm.end():].splitlines():
            if line.startswith((" ", "\t")) and line.strip():
                lines.append(line.strip())
            elif line.strip():
                break
        value = " ".join(lines)
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        value = value[1:-1]
    return value, disabled


def main():
    with open(CONFIG) as f:
        config = json.load(f)
    cursor_skills = next(
        (s["skills"] for s in config["sources"] if s["source"] == UPSTREAM), []
    )
    names = [s for s in cursor_skills if s.startswith("principle-")] + EXPLICIT

    paths = skill_paths()
    rows = []
    for name in names:
        if name not in paths:
            sys.exit(f"ERROR: skill '{name}' not found in {UPSTREAM}")
        text = fetch(f"https://raw.githubusercontent.com/{UPSTREAM}/{BRANCH}/{paths[name]}")
        description, disabled = parse_frontmatter(text)
        if not description:
            sys.exit(f"ERROR: no description in {paths[name]}")
        if not disabled:
            print(f"note: {name} has no disable-model-invocation flag", file=sys.stderr)
        description = description.replace("|", "\\|")
        rows.append(f"| {description} | [{name}](.agents/skills/{name}/SKILL.md) |")

    table = "\n".join(
        ["| When | Read and apply |", "| --- | --- |"] + rows
    )
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write(HEADER + "\n" + table + "\n")
    print(f"wrote {os.path.relpath(OUTPUT, REPO_ROOT)} ({len(rows)} rules)")


if __name__ == "__main__":
    main()
